### ISSUE TITLE
also sync nightshift?

### ISSUE THREAD

**Issue by durandom** [czarny/Brisync#10]
with ddcctl you can also adjust rgb gains. 

```
----- Settings (testing) -----
        -rg <1-..>  [red gain]
        -gg <1-..>  [green gain]
        -bg <1-..>  [blue gain]
        -rrgb       [reset color]
```

At least with my Dell P2715Q it worked:

```
❯ ddcctl -d 1 -rg 1
D: NSScreen #722475023 (2560x1440 0°) HiDPI
I: found 1 external display
I: polling display 1's EDID
I: got edid.serial: V7WP95C1837L
I: got edid.name: DELL P2715Q
D: action: rg: 1
D: setting VCP control #22 => 1
```

Can we read the current rgb shift values of the internal display?

**Comment by Hultner** [comment]
Is this needed? When I enabled night-shift it automatically gets applied to all my monitors. I've never noticed it not syncing properly.

**Comment by durandom** [comment]
Oh, you're right. Just tried it out manually via the system prefs
