### ISSUE TITLE
Brisync stops syncing if monitors have been unplugged for a while (LG Ultrafine 4K)

### ISSUE THREAD

**Issue by Hultner** [czarny/Brisync#17]
I'm using Brisync daily with 3 x LG UltraFine 4K monitors. Whenever I've had the monitors disconnected for a while (e.g. been to a meeting, coming back to my office in the morning) Brisync stops syncing the brightness. 

The "fix" is to restart Brisync every time I've connected my monitors.

I previously used `ddcctl` directly in a script which just ran a loop and applied changes from the internal monitor brightness to all external ones.

**Comment by czarny** [comment]
Can you please test the latest version?
