### ISSUE TITLE
Dell U3219Q

### ISSUE THREAD

**Issue by chavlji** [czarny/Brisync#27]
Works with Dell U3219Q.
Unfortunatelly the brightness matching is really off.
I understand how slider works, but it's not enough in my case.

It would be better if we could set a few matching points (eg. when Mac display is at 0%, 30%, 60%, 100%).

It's impossible to match the brightness with just one factor. At least steep factor would be needed here. Not to mention that monitor's brightness curve is not necessary linear...

Thanks for the effort! Appreciate it very much!

**Comment by czarny** [comment]
I know what you are talking about. I have an idea to add a matching function in the settings. Something like y = log x so you can define any matching curve.

**Comment by czarny** [comment]
Hi, check out the latest version :)

**Comment by chavlji** [comment]
Awesome job!!! Exactly what I was missing! It works great!!! Thanks a ton!
![Screenshot 2020-12-15 at 20 55 09](https://user-images.githubusercontent.com/5729421/102265768-d711d580-3f17-11eb-9513-6b21c3e411ff.jpg)
