### ISSUE TITLE
Syncing brightness with dual / multiple monitor display only modifies one monitor

### ISSUE THREAD

**Issue by jd2476** [czarny/Brisync#30]
I have two Asus ROG VG258 screens connected to my mid 2015 15" MacBook Pro.  One is connected via HDMI directly and the other is connected via HDMI to Thunderbolt 2 active adapter.  When changing brightness (either MBP brightness using Fn+F1/F2 or via brisync menubar control buttons, only one screen, the one connected via HDMI, syncs the brightness.  Not sure what the issue is, but seems brisync isn't compatible with DisplayPort and/or HDMI via Thunderbolt adapter.  I don't have a DisplayPort cable to test directly.
Thank you for an awesome, simple app!

**Comment by czarny** [comment]
I am using Brisync with usbc/hdmi adapter and it works fine. It is hard to say what is the issue in your case. Does app works with only one display connected via adapter to the macbook? Please make sure hdmi cable is fine (it may miss ddc lines). Thanks for feedback.
