### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by andyjw7** [czarny/Brisync#31]
Hi,

Installed today on an MBP 13" 2017 connected to a Dell U2419C monitor via USB-C. The app works great and satisfies my relatively simple use case (which is I want the monitor display to auto adjust with the MBP's display), but the keyboard shortcuts to control only the second display don't appear to work. Is this a defect, or is there some step I need to take to enable this?

Also, could you explain what the 'max brightness value' preference does? I have values of 100 or 255 but swapping between them seems to make no difference.

**Comment by czarny** [comment]
It is hard to say why shortcuts don't work. I assume you are using correct combination (shift + ctrl + f1). Please try restart app and reboot system if it doesn't help you can try find any clue of problem in the system console. I tested shortcuts right now and they works on my machine.

Max brightness value is used to define brightness range. Depending on firmware the display accepts values 0 -100 or 0 - 255. Probably default (100) value is fine for you. If you are not sure which settings you should use check if the app slider settings match values visible in display OSD menu.

**Comment by andyjw7** [comment]
Hi. I figured out the shortcuts. It was actually me not thinking straight! To use F-button functions on a Mac keyboard you need to use the Fn key. I wasn't doing that.

Thanks for the explanation about the brightness range. I've left at 100 and that seems to work fine.
