### ISSUE TITLE
Can't update/install new version

### ISSUE THREAD

**Issue by vorant94** [czarny/Brisync#34]
Hi there! I've used this app for some time. I wanted to update the version from 1.2.0 to 1.3.0 via homebrew, but got an error of SHA256 mismatch. After this I tried to uninstall the app completely and I still have the same problem. Any idea how to solve it?
<img width="682" alt="Screen Shot 2020-12-15 at 22 55 42" src="https://user-images.githubusercontent.com/9719319/102272230-1e549200-3f29-11eb-917e-7cd656b8907f.png">

**Comment by czarny** [comment]
I broke it during v1.3.1 release, should be fine now.

**Comment by vorant94** [comment]
I've forgot to give thanks... so thank you, everything is working fine))
