### ISSUE TITLE
Cinema Display: app slider full brightness == 40% actual max brightness

### ISSUE THREAD

**Issue by sejmann** [czarny/Brisync#6]
While the app does manage to control the brightness of the Apple LED Cinema Display, it only seems to control the lower end of brightness, for some reason.  The mapping looks something like:

slider 0% -> 0% max actual
slider 50% -> 20% max actual
slider 100% -> 40% max actual

It looks like some kind of per-model multiplier might be necessary, but in browsing the source, I don't see any such mechanism or anything that stands out.  Any idea what might cause this effect?

**Comment by czarny** [comment]
Hi, can you please test application with changes added in the cinema branch? If it would resolve the problem I will add application settings.
https://github.com/czarny/Brisync/tree/cinema

**Comment by sejmann** [comment]
Wow, yes, that new version works perfectly.  Thank you!

**Comment by sejmann** [comment]
Actually, I'm not sure the slider display is updated appropriately.   The slider seems pegged at 100% when actual Cinema Display (actual) brightness is >= 40%, even though the actual automatic brightness syncing is working appropriately.  Only a cosmetic issue, however.

**Comment by czarny** [comment]
It was a quick fix for test, it may work only one way for now.

**Comment by czarny** [comment]
Hi, I've added app preferences, let me know does this resolve all problems.
