### ISSUE TITLE
Clamshell mode with Apple Keyboard

### ISSUE THREAD

**Issue by rolandilles** [czarny/Brisync#7]
Hey, first of all: nifty little app! Is there any way to make this work in clamshell mode (i.e. with the MacBook's lid closed and monitors attached) and with an Apple Keyboard's brightness keys? The external keyboard works as expected with the lid open because the app can replicate the MacBook's brightness, but once the lid is closed I can only adjust it from the menu bar, there's no reaction to the keyboard's brightness keys.

**Comment by IgorMuzyka** [comment]
@rale09 To achieve this it would probably be convenient to check with CGEvent's from the keyboard which corespond with the brightness up/down and trigger an update of brightness when capturing them, but consider the internal or a built-in display would probably give no brightness or 0.

**Comment by czarny** [comment]
Hi, I've added hotkeys.
Brightness down ⇧ + ⌃ + F1
Brightness up      ⇧ + ⌃ + F2
Fell free to update app https://github.com/czarny/Brisync/releases/tag/v1.2.0

**Comment by IgorMuzyka** [comment]
@czarny is there some actual pull request or you just metioned the shortcuts you wish to be triggering the extrnal monitor brightness?

**Comment by czarny** [comment]
I just created a new release https://github.com/czarny/Brisync/releases/tag/v1.2.0

**Comment by maelcum** [comment]
> Brightness down ⇧ + ⌃ + F1
> Brightness up ⇧ + ⌃ + F2

Great! Works on a MacBook Pro with the Alienware AW3418DW.
It would be great to add the Info about Shift+Ctrl+F1/F2 to the GitHub-ReadMe/Frontpage.
